name: Backend CI/CD Pipeline

on:
  push:
    paths:
      - 'backend/**'  # Триггер на изменения в директории backend
    branches:
      - release-0.0.1

stages:
  - build
  - notify

jobs:
  build-backend:
    stage: build
    runs-on: ubuntu-latest
    only:
      changes:
        - 'backend/**'  # Запускать только если есть изменения в backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      - name: Build backend with Maven
        run: |
          cd backend
          mvn package
    artifacts:
      paths:
        - 'backend/target/*.jar'  # Сохранение артефактов сборки (JAR-файл)

  telegram-notification-backend:
    stage: notify
    runs-on: ubuntu-latest
    needs: build-backend  # Запускать только после успешной сборки
    if: github.event.head_commit.message == 'send notification'  # Проверка на наличие текста "send notification" в сообщении коммита
    steps:
      - name: Send Telegram notification
        run: |
          curl -X POST \
          -H 'Content-Type: application/json' \
          -d '{"chat_id": "-1002405712257", "text": "Build successful! JAR file: <URL_TO_YOUR_JAR_FILE>"}' \
          https://api.telegram.org/bot7642134915:AAFUUwcZ-GW7d0WBAJx7qxKqCjiRM6NrEpQ/sendMessage
