name: Main Pipeline

on:
  push:
    branches:
       - main

jobs:
  include-backend:
    name: Include Backend Workflow
    uses: ./.github/workflows/backend.yml
  
  include-frontend:
    name: Include Frontend Workflow
    uses: ./.github/workflows/frontend.yml