name: Main Pipeline

on:
  push:
    branches:
       - main
    paths:
      - 'backend/**'  
      - 'frontend/**'

jobs:
  backend:
    name: Include Backend Workflow
    uses: ./.github/workflows/backend.yml
  
  frontend:
    name: Include Frontend Workflow
    uses: ./.github/workflows/frontend.yml