name: Backend Build & Notify

on:
  workflow_dispatch: # Позволяет запуск вручную     
  push:
    paths:
      - 'backend/**'  # Триггер на изменения в директории backend
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17 for backend
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build backend with Maven
        run: |
          cd backend
          mvn clean package

      - name: Send Telegram notification
        run: |
          curl -X POST \
          -H 'Content-Type: application/json' \
          -d '{"chat_id": "-1002405712257", "text": "Backend Build successful! JAR file: <URL_TO_YOUR_JAR_FILE>"}' \
          https://api.telegram.org/bot7642134915:AAFUUwcZ-GW7d0WBAJx7qxKqCjiRM6NrEpQ/sendMessage
